// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem;

#nullable disable

namespace RestaurantHotelBookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(RestaurantSystemContext))]
    [Migration("20241231101858_editcolumntype")]
    partial class editcolumntype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.ExceptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallStackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExceptionLogId")
                        .HasColumnType("int");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.FoodType", b =>
                {
                    b.Property<int>("FoodTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodTypeId");

                    b.ToTable("FoodType");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.MealCategory", b =>
                {
                    b.Property<int>("MealCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealCategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MealCategoryId");

                    b.ToTable("MealCategory");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.MealOptions", b =>
                {
                    b.Property<int>("MealOptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealOptionsId"));

                    b.Property<int>("FoodTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MealCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MealOptionsId");

                    b.HasIndex("FoodTypeId");

                    b.HasIndex("MealCategoryId");

                    b.ToTable("MealOptions");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.People", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("RolesId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealOptionsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VegNonVeg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantId");

                    b.HasIndex("MealOptionsId");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolesId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.MealOptions", b =>
                {
                    b.HasOne("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.FoodType", "FoodType")
                        .WithMany()
                        .HasForeignKey("FoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.MealCategory", "MealCategory")
                        .WithMany()
                        .HasForeignKey("MealCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodType");

                    b.Navigation("MealCategory");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.People", b =>
                {
                    b.HasOne("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.Roles", "Roles")
                        .WithMany("People")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.Restaurant", b =>
                {
                    b.HasOne("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.MealOptions", "mealOptions")
                        .WithMany()
                        .HasForeignKey("MealOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mealOptions");
                });

            modelBuilder.Entity("RestaurantHotelBookingSystem.Infrastructure.RestaurantSystem.Tables.Roles", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
